import { builtinModules } from "node:module";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig(({ mode }) => {
	const prod = mode === "production";

	return {
		plugins: [
			vue(),
			{
				name: "obsidian-main-banner",
				apply: "build",
				enforce: "post",
				async closeBundle() {
					const outputPath = path.resolve(process.cwd(), "main.js");
					const source = await readFile(outputPath, "utf8");

					if (source.startsWith(banner)) {
						return;
					}

					await writeFile(outputPath, `${banner}${source}`, "utf8");
				},
			},
		],
		build: {
			lib: {
				entry: "src/main.ts",
				formats: ["cjs"],
				fileName: () => "main.js",
			},
			outDir: ".",
			emptyOutDir: false,
			target: "es2018",
			sourcemap: prod ? false : "inline",
			minify: prod ? "esbuild" : false,
			rollupOptions: {
				external: [
					"obsidian",
					"electron",
					"@codemirror/autocomplete",
					"@codemirror/collab",
					"@codemirror/commands",
					"@codemirror/language",
					"@codemirror/lint",
					"@codemirror/search",
					"@codemirror/state",
					"@codemirror/view",
					"@lezer/common",
					"@lezer/highlight",
					"@lezer/lr",
					...builtinModules,
				],
				output: {
					exports: "default",
				},
			},
		},
	};
});
